# permissions for end users to edit wansyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wansync-editor-role
rules:
- apiGroups:
  - hazelcast.com
  resources:
  - wansyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hazelcast.com
  resources:
  - wansyncs/status
  verbs:
  - get
