apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  repository: "docker.io/hazelcast/hazelcast-enterprise"
  version: "5.2.1"
  licenseKeySecretName: hazelcast-license-key
  tls:
    secretName: example
