name: Check Breaking Changes

on: [workflow_dispatch]

jobs:
  check_breaking_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run check for breaking changes
      working-directory: tools/version-diff-tool
      run: |
        BASE="5.6"  # Set your base version here or pass it as an input
        REVISION="5.7"  # Set your revision version here or pass it as an input
        OUTPUT=$(go run main.go -base $BASE -revision $REVISION)

        # Check for "0 breaking changes"
        if echo "$OUTPUT" | grep -q "0 breaking changes"; then
          echo "No breaking changes found."
        else
          echo $OUTPUT
          exit 1
        fi
