name: Check Breaking Changes

on: [workflow_dispatch]

env:
  HELM_REPO_NAME: operator
  HELM_REPO_URL: https://hazelcast-charts.s3.amazonaws.com
  
jobs:
  check_breaking_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22.3"    

    - name: Run check for breaking changes
      working-directory: tools/version-diff-tool
      run: |
        helm repo add operator https://hazelcast-charts.s3.amazonaws.com && helm repo update && \
        BASE="5.7"  
        REVISION="5.8"  
        helm template operator hazelcast/hazelcast-platform-operator-crds --version=$BASE > $BASE.yaml
        helm template operator hazelcast/hazelcast-platform-operator-crds --version=$REVISION > $REVISION.yaml
        OUTPUT=$(go run main.go -base $BASE -revision $REVISION)

        # Check for "0 breaking changes"
        if echo "$OUTPUT" | grep -q "0 breaking changes"; then
          echo "No breaking changes found."
        else
          echo $OUTPUT
          exit 1
        fi
