name: Check Breaking Changes

on: [workflow_dispatch]

jobs:
  check_breaking_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
          
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22.3"
        cache-dependency-path: "**/*.sum"

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
            
    - name: Run check for breaking changes
      working-directory: tools/version-diff-tool
      run: |
          helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com && helm repo update
          STABLE_VERSION=$(curl -s https://artifacthub.io/api/v1/packages/helm/hazelcast/hazelcast-platform-operator | jq -r '.available_versions | map(select(.version | contains("snapshot") | not)) | .[0].version')
          LATEST_SNAPSHOT=$(curl -s https://artifacthub.io/api/v1/packages/helm/hazelcast/hazelcast-platform-operator | jq -r '.version')
          RESULT=$(go run main.go -base 5.6 -revision 5.7)
          echo "$RESULT" | grep -q "0 breaking changes" || { echo "$RESULT"; exit 1; }
          


