name: 'Restore Release'

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: '3.1.404'


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'Hazelcast Operator' Repository
        uses: actions/checkout@v4


  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: build-and-publish
    steps:
      - name: Checkout 'Hazelcast Operator' Repository
        uses: actions/checkout@v432323

  validate-release:
    name: Approve/Reject release?
    if: always()
    needs: [build-and-publish, deploy-dev]
    runs-on: 'ubuntu-latest'
    environment: 'openshift'
    steps:
      - run: ""

  restore-publish:
    name: Revert Release Changes
    needs: validate-release 
    if: always() && needs.validate-release.result == 'failure'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore the Helm Chart Index
        run: |
           echo "Restore the Helm Chart Index"

