name: 'Restore Release'

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: '3.1.404'


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'Hazelcast Operator' Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: build-and-publish
    steps:
      - name: Checkout 'Hazelcast Operator' Repository
        uses: actions/checkout@v4

  validate-release:
    name: Approve/Reject release?
    needs: [build-and-publish, deploy-dev]
    runs-on: 'ubuntu-latest'
    environment: 'openshift'
    steps:
      - run: ""

  restore-publish:
    name: Revert Release Changes
    if: always() && contains(needs.validate-release.result, 'failure')
    needs: [validate-release]
    runs-on: 'ubuntu-latest'
    environment: 'openshift'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore the Helm Chart Index
        run: |
           echo "Restore the Helm Chart Index"
